2022-10-18 00:35:55,139:DEBUG:certbot._internal.main:certbot version: 1.29.0
2022-10-18 00:35:55,139:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/lib/python-exec/python3.9/certbot
2022-10-18 00:35:55,139:DEBUG:certbot._internal.main:Arguments: ['--dry-run', '--config-dir=certbot/config', '--work-dir=certbot/work', '--logs-dir=certbot/logs']
2022-10-18 00:35:55,139:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-10-18 00:35:55,146:DEBUG:certbot._internal.log:Root logging level set at 30
2022-10-18 00:35:55,147:DEBUG:certbot._internal.plugins.selection:Requested authenticator None and installer None
2022-10-18 00:35:55,157:ERROR:certbot.util:Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [alert] could not open error log file: open() "/var/log/nginx/error_log" failed (13: Permission denied)
2022/10/18 00:35:55 [warn] 1355082#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2022/10/18 00:35:55 [emerg] 1355082#0: cannot load certificate "/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed

2022-10-18 00:35:55,157:DEBUG:certbot._internal.plugins.disco:Misconfigured PluginEntryPoint#nginx: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [alert] could not open error log file: open() "/var/log/nginx/error_log" failed (13: Permission denied)
2022/10/18 00:35:55 [warn] 1355082#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2022/10/18 00:35:55 [emerg] 1355082#0: cannot load certificate "/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/certbot_nginx/_internal/configurator.py", line 999, in config_test
    util.run_script([self.conf('ctl'), "-c", self.nginx_conf, "-t"])
  File "/usr/lib/python3.9/site-packages/certbot/util.py", line 121, in run_script
    raise errors.SubprocessError(msg)
certbot.errors.SubprocessError: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [alert] could not open error log file: open() "/var/log/nginx/error_log" failed (13: Permission denied)
2022/10/18 00:35:55 [warn] 1355082#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2022/10/18 00:35:55 [emerg] 1355082#0: cannot load certificate "/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/certbot/_internal/plugins/disco.py", line 160, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3.9/site-packages/certbot_nginx/_internal/configurator.py", line 199, in prepare
    self.config_test()
  File "/usr/lib/python3.9/site-packages/certbot_nginx/_internal/configurator.py", line 1001, in config_test
    raise errors.MisconfigurationError(str(err))
certbot.errors.MisconfigurationError: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [alert] could not open error log file: open() "/var/log/nginx/error_log" failed (13: Permission denied)
2022/10/18 00:35:55 [warn] 1355082#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2022/10/18 00:35:55 [emerg] 1355082#0: cannot load certificate "/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed

2022-10-18 00:35:55,158:DEBUG:certbot._internal.plugins.selection:Multiple candidate plugins: * nginx
Description: Nginx Web Server plugin
Interfaces: Installer, Authenticator, Plugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f4172b9e970>
Prep: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [alert] could not open error log file: open() "/var/log/nginx/error_log" failed (13: Permission denied)
2022/10/18 00:35:55 [warn] 1355082#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2022/10/18 00:35:55 [emerg] 1355082#0: cannot load certificate "/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/dev.conjure.dev/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed


* standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7f4172bf1f70>
Prep: True

* webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f4172bf1f40>
Prep: True
2022-10-18 00:36:49,636:ERROR:certbot._internal.log:Exiting due to user request.
